simulation_end_time_ns=[SIMULATION-END-TIME-NS]
traffic_stop_time_ns=[TRAFFIC-STOP-TIME-NS]
drain_time_ns=[DRAIN-TIME-NS]
simulation_seed=123456789

satellite_network_dir="../../../../../satellite_networks_state/gen_data/[SATELLITE-NETWORK]"
satellite_network_routes_dir="[DYNAMIC-STATE]"
dynamic_state_algorithm=[DYNAMIC-STATE-ALGORITHM]
dynamic_state_update_interval_ns=[DYNAMIC-STATE-UPDATE-INTERVAL-NS]

isl_data_rate_megabit_per_s=[ISL-DATA-RATE-MEGABIT-PER-S]
gsl_data_rate_megabit_per_s=[GSL-DATA-RATE-MEGABIT-PER-S]
isl_max_queue_size_pkts=[ISL-MAX-QUEUE-SIZE-PKTS]
gsl_max_queue_size_pkts=[GSL-MAX-QUEUE-SIZE-PKTS]

enable_isl_utilization_tracking=[ENABLE-ISL-UTILIZATION-TRACKING]
[ISL-UTILIZATION-TRACKING-INTERVAL-NS-COMPLETE]

enable_link_queue_tracking=[ENABLE-LINK-QUEUE-TRACKING]
enable_physical_link_drop_tracking=[ENABLE-PHYSICAL-LINK-DROP-TRACKING]

tcp_socket_type=TcpNewReno
enable_tcp_flow_scheduler=false

enable_udp_burst_scheduler=true
udp_burst_schedule_filename="udp_burst_schedule.csv"
udp_burst_enable_logging_for_udp_burst_ids=[UDP-BURST-LOGGING-SET]

enable_pingmesh_scheduler=false
