simulation_end_time_ns=[SIMULATION-END-TIME-NS]
simulation_seed=123456789

satellite_network_dir="../../../../../satellite_networks_state/gen_data/[SATELLITE-NETWORK]"
satellite_network_routes_dir="[DYNAMIC-STATE]"
dynamic_state_algorithm=[DYNAMIC-STATE-ALGORITHM]
dynamic_state_update_interval_ns=[DYNAMIC-STATE-UPDATE-INTERVAL-NS]

isl_data_rate_megabit_per_s=[ISL-DATA-RATE-MEGABIT-PER-S]
gsl_data_rate_megabit_per_s=[GSL-DATA-RATE-MEGABIT-PER-S]
isl_max_queue_size_pkts=[ISL-MAX-QUEUE-SIZE-PKTS]
gsl_max_queue_size_pkts=[GSL-MAX-QUEUE-SIZE-PKTS]

enable_isl_utilization_tracking=[ENABLE-ISL-UTILIZATION-TRACKING]
[ISL-UTILIZATION-TRACKING-INTERVAL-NS-COMPLETE]

enable_link_queue_tracking=[ENABLE-LINK-QUEUE-TRACKING]

tcp_socket_type=TcpNewReno

enable_tcp_flow_scheduler=true
tcp_flow_schedule_filename="schedule_oneweb_1200.csv"
tcp_flow_enable_logging_for_tcp_flow_ids=set(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87)